pip install colorama
pip install numpy
pip instal discum
pip install requests
pip install sys
pip install time
pip install threading
pip install random
pip install json
pip install os
pip install pyfiglet
pip install time
pip install re
pip install http.client
pip install string
pip install ctypes
pip install concurrent.features
pip install socket
pip install pyfade
pip install websocket
pip install concurrent.futures
pip install emoji
pip install base64 